# Generated by Django 5.0.4 on 2024-05-16 08:27

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_image_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.TextField()),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("file_location", models.FileField(upload_to=core.models.picture_path)),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
