# Generated by Django 5.0.4 on 2024-05-16 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_uploadedimage_delete_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedimage",
            old_name="original_name",
            new_name="name",
        ),
    ]
