# Generated by Django 5.0.4 on 2024-05-21 08:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_uploadedimage_file_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="file_location",
            field=models.FileField(upload_to=core.models.UploadedImage.upload_to),
        ),
    ]
