# Generated by Django 5.0.6 on 2024-06-07 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_uploadedimage_file_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="id",
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="DVLayerTifPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wavelength", models.CharField(max_length=30)),
                ("file_location", models.ImageField(upload_to="")),
                (
                    "uploaded_image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.uploadedimage",
                    ),
                ),
            ],
        ),
    ]
