# Generated by Django 5.0.6 on 2024-06-07 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_uploadedimage_id_alter_uploadedimage_uuid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dvlayertifpreview",
            old_name="uploaded_image_id",
            new_name="uploaded_image_uuid",
        ),
    ]
