# Generated by Django 5.0.6 on 2024-07-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_uploaded_image_id_dvlayertifpreview_uploaded_image_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentedImage',
            fields=[
                ('UUID', models.UUIDField(primary_key=True, serialize=False)),
                ('ImagePath', models.FilePathField()),
                ('CellPairPrefix', models.FilePathField()),
                ('NumCells', models.IntegerField()),
            ],
        ),
    ]
