# Generated by Django 5.0.6 on 2024-10-28 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_segmentedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
                ('distance', models.FloatField()),
                ('line_gfp_intensity', models.FloatField()),
                ('nucleus_intensity_sum', models.FloatField()),
                ('cellular_intensity_sum', models.FloatField()),
                ('segmented_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.segmentedimage')),
            ],
        ),
    ]
